version: '3.9'

services:
  db:
    restart: always
    image: postgres
    env_file:
      - .env
    expose:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver"
    ports:
      - '8000:8000'

  redis:
    image: redis
    expose:
      - '6379'
    env_file:
      - .env

  celery:
    build: .
    command:  >
      bash -c "celery -A config worker --beat --loglevel=info"
    volumes:
      - .:/code
    depends_on:
      - app
      - redis

  celery_beat:
    build: .
    tty: true
    command: celery -A config beat -l INFO -S django
    depends_on:
      - redis

volumes:
  postgres_data: