# Generated by Django 5.0.3 on 2024-03-11 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=150, null=True, verbose_name='место')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='время')),
                ('action', models.CharField(blank=True, max_length=300, null=True, verbose_name='действие')),
                ('pleasant', models.BooleanField(verbose_name='приятная')),
                ('period', models.CharField(blank=True, choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно')], default='daily', max_length=20, null=True, verbose_name='период')),
                ('award', models.CharField(blank=True, max_length=255, null=True, verbose_name='вознаграждение')),
                ('run_time', models.IntegerField(default=0, verbose_name='время выполнения')),
                ('public', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель')),
                ('related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.habit', verbose_name='связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
